test_that("palette lookups work", {
  expect_true("伊内丝" %in% ak_names())
  expect_true("CONFESS-47" %in% ak_names())
  expect_false("CONFESS-47" %in% ak_names(rarity = 6))
  expect_length(ak_palette("伊内丝", 6), 6)
  expect_length(ak_palette("CONFESS-47", 6), 6)
  expect_length(ak_sequential("伊内丝", 16), 16)
  expect_length(ak_diverging("伊内丝", 17), 17)
  expect_true("伊内丝" %in% arkplatte_names())
  expect_length(arkplatte("伊内丝", 6), 6)
  expect_length(arkplatte_seq("伊内丝", 16), 16)
  expect_length(arkplatte_div("伊内丝", 17), 17)
  expect_length(arkplatte_cat(4), 4)
})
